// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sgliigycmxmnbgrcrurf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnbGlpZ3ljbXhtbmJncmNydXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNjgwMDIsImV4cCI6MjA2ODk0NDAwMn0.kO4UVHbidgp3nS7izImH9QR7cl-HTIng1ZW9ob7dvsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});